# Generated by Django 5.0.4 on 2024-05-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_project_alter_testimonial_image_projectimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImagePanorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/panoramas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='backend_api.project')),
            ],
        ),
    ]
