# Generated by Django 5.0.4 on 2024-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_projectimagepanorama'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimagepanorama',
            name='name',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
